package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/spolnik/RepoKarta/internal/apicontract"
)

type namedType struct {
	name  string
	value any
}

func main() {
	output := flag.String("output", "", "generated TypeScript output path")
	flag.Parse()
	if strings.TrimSpace(*output) == "" {
		fmt.Fprintln(os.Stderr, "-output is required")
		os.Exit(2)
	}

	types := []namedType{
		{name: "APIErrorResponse", value: apicontract.ErrorResponse{}},
		{name: "ArtifactProgressResponse", value: apicontract.ArtifactProgress{}},
		{name: "ConversationEvent", value: apicontract.ConversationEvent{}},
		{name: "DependencyRefreshProgressResponse", value: apicontract.DependencyRefreshProgress{}},
		{name: "HealthResponse", value: apicontract.HealthResponse{}},
		{name: "ProviderStatusesResponse", value: apicontract.ProviderStatusesResponse{}},
		{name: "WikiPageResponse", value: apicontract.WikiPage{}},
		{name: "WikiSiteResponse", value: apicontract.WikiSite{}},
	}
	sort.Slice(types, func(left, right int) bool {
		return types[left].name < types[right].name
	})

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go generate ./internal/apicontract; DO NOT EDIT.\n")
	generated.WriteString("// The Go JSON structs are authoritative.\n\n")
	for _, current := range types {
		generated.WriteString("export type ")
		generated.WriteString(current.name)
		generated.WriteString(" = ")
		generated.WriteString(renderType(reflect.TypeOf(current.value), 0))
		generated.WriteString(";\n\n")
	}

	target, err := filepath.Abs(*output)
	if err != nil {
		fatalf("resolve output: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	outputBytes := bytes.TrimSuffix(generated.Bytes(), []byte("\n"))
	if err := os.WriteFile(target, outputBytes, 0o644); err != nil {
		fatalf("write generated contracts: %v", err)
	}
}

func renderType(value reflect.Type, indent int) string {
	if value == reflect.TypeOf(time.Time{}) {
		return "string"
	}
	if value.Kind() == reflect.Pointer {
		return renderType(value.Elem(), indent) + " | null"
	}
	switch value.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Interface:
		return "unknown"
	case reflect.Slice, reflect.Array:
		if value.Elem().Kind() == reflect.Uint8 {
			return "string"
		}
		return "Array<" + renderType(value.Elem(), indent) + ">"
	case reflect.Map:
		if value.Key().Kind() != reflect.String {
			return "unknown"
		}
		return "Record<string, " + renderType(value.Elem(), indent) + ">"
	case reflect.Struct:
		var result strings.Builder
		result.WriteString("{\n")
		for index := 0; index < value.NumField(); index++ {
			field := value.Field(index)
			jsonName, optional, include := jsonField(field)
			if !include {
				continue
			}
			result.WriteString(strings.Repeat("  ", indent+1))
			result.WriteString(jsonName)
			if optional {
				result.WriteString("?")
			}
			result.WriteString(": ")
			result.WriteString(renderType(field.Type, indent+1))
			result.WriteString(";\n")
		}
		result.WriteString(strings.Repeat("  ", indent))
		result.WriteString("}")
		return result.String()
	default:
		return "unknown"
	}
}

func jsonField(field reflect.StructField) (string, bool, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		if field.Anonymous {
			return "", false, false
		}
		name = field.Name
	}
	optional := false
	for _, option := range parts[1:] {
		if option == "omitempty" {
			optional = true
		}
	}
	return name, optional, true
}

func fatalf(template string, arguments ...any) {
	fmt.Fprintf(os.Stderr, template+"\n", arguments...)
	os.Exit(1)
}
